services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=guedes
      - MONGO_INITDB_ROOT_PASSWORD=guedes
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local